### ISSUE TITLE
Add 315°C support for  V2016040401

### ISSUE THREAD

**Issue by ra100** [donovan6000/M3D-Fio#126]
can you add high tempereture support to newest firmware? Thanks.

**Comment by donovan6000** [comment]
People were complaining about having to flash the firmware everytime they switched between using M3D Fio and the official software due to the version number I used in the last 315°C firmware, so I M3D Fio now includes both unmodified and modified versions of the firmware.

The M3D Mod firmwares have the temperatures increased, so M3D Mod V2016040401 is what your looking for.
![mod](https://cloud.githubusercontent.com/assets/6620767/14403176/5b3079b8-fe02-11e5-9084-f42a9a685273.png)

**Comment by ra100** [comment]
Well, that's interesting, I don't have Mod version in menu, but nevermind, I just went through files, and I can flash it from .hex file.
![screenshot-192 168 150 12 5000 2016-04-09 12-42-22](https://cloud.githubusercontent.com/assets/3185410/14403254/9096b09c-fe50-11e5-9b32-1560fb0a64c7.png)

**Comment by ra100** [comment]
I forgot to remove build/ dist/ and OctoPrint_M3DFio.egg-info/ folders before python setup.py install. Sorry.
