### ISSUE TITLE
Slicing profile gets deleted after slicing

### ISSUE THREAD

**Issue by ra100** [donovan6000/M3D-Fio#15]
I know, that tihs is not finished yet, but when I use my custom slicing profile, it gets removed after model is sliced. I need to copy that profile again to profiles folder.

**Comment by donovan6000** [comment]
How the slicing works is that it'll backup the original slicer profile, model, and printer profile before replacing them so that the slicer uses the modified version of each. Then it should restored the backups after the slicer succeeds, fails, or it cancels. So I'm not sure why it's not restoring your slicer profile. I'll look into this more later today.

**Comment by donovan6000** [comment]
Haven't been able to recreate this issue. Do you have a link to the profile your using?

**Comment by ra100** [comment]
This is the profile https://github.com/ra100/M3D-slicing-profiles/blob/master/cura/m3d_pla_0.1mm_brim.profile, it's just modified m3d_pla_0.1mm.profile, changed temperature and platform_adhesion

**Comment by ra100** [comment]
tried it again, seems OK.
