### ISSUE TITLE
Z offset

### ISSUE THREAD

**Issue by qwerty8224** [donovan6000/M3D-Fio#157]
You can add management Z-offset while printing?
It is very convenient to pick up the height of the first layer at the beginning of printing.

**Comment by donovan6000** [comment]
If your bed is calibrated accurately then there shouldn't be any reason to do this since it would cause the first layer to not stick to the bed.

You can achieve what your asking for by changing some of the slicer settings. If your using Cura, you can decrease the 'bottom_thickness' setting and increase M3D Fio's bed height offset setting.
