### ISSUE TITLE
Suggest re-labelling the "Complete Bed Calibration" button ...

### ISSUE THREAD

**Issue by domwakeling** [donovan6000/M3D-Fio#19]
... going through a clean install to see whether I can overcome my temperature/quality issues, and having run through the calibration steps I tapped on the "complete ..." button in order to finish the calibration process ... and then realised that it's now going to run the complete process from scratch!

It's not a mistake that anyone's going to make twice, but maybe add the word "Run" at the start?

**Comment by donovan6000** [comment]
It should pop up a dialog box saying 'This process can take a while to complete and will require your input during some steps. Proceed?' which I hoped would warn people. The 'complete bed calibration' button preforms the following: automatically calibrating bed center Z0, automatically calibrating bed orientation, and manually calibrating the four corner offsets. It's the only button you'll ever need for bed calibrating.

I've renamed the button though since I see your point.
