### ISSUE TITLE
Cannot manually change bed orientation

### ISSUE THREAD

**Issue by ep1cman** [donovan6000/M3D-Fio#26]
When I attempt to change the values for bed orientations in the M3D-Fio settings pannel and reload they return to their previous value. Here is a snippet from the terminal when I try to change the values:

Send: M618 S5 P3218932656
Send: M619 S5
Recv: ok Target address out of range
Recv: ok
Recv: ok  PT:5 DT:-1076034652

This is from chaning the Front Right Orientation from "1.726674" to "1.726675"

**Comment by donovan6000** [comment]
Turns out that the printer's firmware doesn't let us manually change any of the bed orientation values, and there's nothing we can really do about that. So I've disabled editing those values in M3D Fio's settings.

We'll just have to hope that the printer's automatic bed orientation calibration does a good enough job.
