### ISSUE TITLE
Cannot print this gcode, error indicates print too large

### ISSUE THREAD

**Issue by LogicalChaos** [donovan6000/M3D-Fio#40]
This vertical 80x80x6 lithoframe fails to print with an error of print too large.   The M3D Printer Profile in OctoPi is 113x107x112.  When I print the same gcode file in [MicroPrint](https://github.com/tomasf/microprint), it prints as expected.  The slicer doesn't appear to make a difference, tried Simplify3D and Cura (external).  I've not tried the embedded Cura engine.

[litho.gcode.zip](https://github.com/donovan6000/M3D-Fio/files/85252/litho.gcode.zip)

**Comment by donovan6000** [comment]
M3D Fio enforces the same three tier boundary limitations as the official software, which has the top tier shifted toward the left for some reason. I probably should strive away from the boundaries that M3D's software uses since they're kinda weird.
![boundaries](https://cloud.githubusercontent.com/assets/6620767/12283896/d8abd55a-b95f-11e5-8cbf-4e982a0b8acd.png)

microprint seems to enforce the boundary limitations from this image, which I don't think the official software has ever used as boundary limitations.
![boundaries](https://images-na.ssl-images-amazon.com/images/S/aplus-seller-content-images-us-east-1/ATVPDKIKX0DER/AHFLO9ZY5J98/B017HWRNKI/LNt9NJNSbCG._SX300_.png)

As a temporary fix, you can enable the 'Ignore print dimension limitations' option in OctoPrint settings under the M3D Fio tab which will allow you to print anything.

**Comment by LogicalChaos** [comment]
> On Jan 12, 2016, at 8:27 PM, donovan6000 <notifications@github.com> wrote:
> 
> M3D Fio enforces the same three tier boundary limitations as the official software, which has the top tier shifted toward the left for some reason. I probably should strive away from the boundaries that M3D's software uses since they're kinda weird.
> 
Hmmm…  When I throw the stl into the embedded slicer, even translated over, it never fits.  The object is 80x80, so it should.  I have to rotate around Z (45 works) after translating to get it happy.  I’d not seen the bounding box before in the Modify Model pane.  Nice work!
> microprint seems to enforce the boundary limitations from this image, which I don't think the official software has ever used as boundary limitations.
> 
This is the one I’m familiar with.
>  <https://camo.githubusercontent.com/614dc63ff2b9bffb174b28ef4a87b08f784d497a/68747470733a2f2f696d616765732d6e612e73736c2d696d616765732d616d617a6f6e2e636f6d2f696d616765732f532f61706c75732d73656c6c65722d636f6e74656e742d696d616765732d75732d656173742d312f41545650444b494b58304445522f4148464c4f395a59354a39382f423031374857524e4b492f4c4e74394e4a4e536243472e5f53583330305f2e706e67>
> As a temporary fix, you can enable the 'Ignore print dimension limitations' option in OctoPrint settings under the M3D Fio tab which will allow you to print anything
> 

I had tried that, and the print went south almost immediately.  Although that was on .23.  I’ll try it again on .24.3

Thanks,
Rob

**Comment by donovan6000** [comment]
So I did some tests today, and ended up deciding on these new boundaries.
![bound](https://cloud.githubusercontent.com/assets/6620767/12315634/2f9d00fa-ba32-11e5-9d49-0a56f1f0e5f8.png)

The litho.gcode files still goes out of bounds with them though because of the command 'G1 X0 F2160' on line 455977. This moves the extruder to X0 when it's in the top tier, and the lowest X can be there is 7. So if you change it to something with a higher X, like 'G1 X54 F2160', then it'll print.

**Comment by LogicalChaos** [comment]
I'll try this out when I pull later today.  Thanks.

**Comment by LogicalChaos** [comment]
Yup, that takes care of it.  Thanks.  I'm presuming you know about the odd little step up in the bounding box at the front?

**Comment by donovan6000** [comment]
That new boundary box is based on where the tip of the extruder can physically be. It can go slightly past the front of the print bed which would allow it to print on the actual frame of the printer, so the step up at the front is to make sure that the start of the print is on the bed and not the frame.

**Comment by LogicalChaos** [comment]
Makes sense.  I have a nice divot on the frame of the printer showing where it can go :-)
