### ISSUE TITLE
During complete calibration head didn't move to FR and BL corner

### ISSUE THREAD

**Issue by ra100** [donovan6000/M3D-Fio#58]
In manual calibration phase on complete bed calibration, head didn't move to Front Right and Back Left corner.

**Comment by donovan6000** [comment]
This is a result of the printer ignoring some commands in a non repeatable way, and it's related to the double homing issue that we just fixed. I've tried a lot in the past to overcome this issue. So now it'll send the [absolute command G90 twice, which will actually get sent 4 times because M3D Fio already sends it twice, and the movement command G0 twice](https://github.com/donovan6000/M3D-Fio/blob/devel/octoprint_m3dfio/static/js/m3dfio.js#L5784-L5789). There's already G4 commands and delays that get sent in between sending commands, so hopefully all these things combined will fix this problem.

**Comment by ra100** [comment]
Just tried it, works fine.

**Comment by ra100** [comment]
Well almost, I just looked at settings, and bed offsets are set to 0.
serial.log https://gist.github.com/ra100/7a222cdf200ee1758d93

**Comment by ra100** [comment]
bed offset values are being saved saved
